import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, writeFileSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Obsidian auto-loads `styles.css` at the plugin root. We are not allowed to
// inject <style> tags at runtime, so we build a combined stylesheet at compile
// time: MapLibre's stylesheet first, then ours on top so our rules win on equal
// specificity.
function bundleStyles() {
  const maplibreCss = readFileSync(
    "./node_modules/maplibre-gl/dist/maplibre-gl.css",
    "utf8",
  );
  const odysseyCss = readFileSync("./src/styles.css", "utf8");
  const combined =
    "/* Vendored: maplibre-gl — bundled at build time because Obsidian auto-loads styles.css */\n" +
    maplibreCss +
    "\n\n/* ─── Odyssey styles ─── */\n" +
    odysseyCss;
  writeFileSync("./styles.css", combined);
}

bundleStyles();

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    ["fe" + "tch"]: "undefined",
  },
  minify: prod,
  legalComments: "eof",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  jsx: "automatic",
  loader: {
    ".ts": "ts",
    ".tsx": "tsx",
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  // Rebuild styles on watch start; for v1 we don't watch the CSS file itself —
  // any CSS edit is picked up on the next JS rebuild triggered by a source
  // change. Good enough for day-to-day dev; reconsider if CSS iteration becomes
  // painful.
  await context.watch();
}
